### ISSUE TITLE
Error in Make process: 'No such file or directory'

### ISSUE THREAD

**Issue by michaelyma12** [turi-code/python-libffm#10]
I am running the quick start procedures on Windows terminal. After I do 'cd ffm' and then 'make', I receive the following error:

'fatal error: parallel/winpthreadsll.h: No such file or directory' 

I attached a screenshot of the full output below. 

![ffmscreen](https://cloud.githubusercontent.com/assets/19233359/22535825/87d86fa2-e8b2-11e6-82f4-ad8ea71548f6.JPG)

**Comment by lawlite19** [comment]
I have the same error. How did you solve it?
