### ISSUE TITLE
compile error from Ubuntu system

### ISSUE THREAD

**Issue by ajing** [turi-code/python-libffm#3]
I guess I don't have all dependencies install. I have installed graph lab create. But here is my error:

g++ -o libffm.so -O3 -std=c++11 -I ../sdk -shared -fPIC -march=native -fopenmp src/libffm.cpp lib/ffm.o 
src/libffm.cpp: In function 'graphlab::gl_sarray predict_sframe(ffm::ffm_model_, graphlab::gl_sframe, std::string, std::vectorstd::basic_string<char >)':
src/libffm.cpp:53:63: error: call of overloaded 'get_column_index(graphlab::gl_sframe&, std::string&)' is ambiguous
   size_t target_col_idx = get_column_index(data, target_column); 
                                                               ^
src/libffm.cpp:53:63: note: candidates are:
src/libffm.cpp:22:8: note: size_t get_column_index(graphlab::gl_sframe, std::string)
 size_t get_column_index(gl_sframe sf, string colname) {
        ^
In file included from src/libffm.cpp:16:0:
../sdk/../ffm/lib/ffm.h:22:8: note: size_t ffm::get_column_index(graphlab::gl_sframe, std::string)
 size_t get_column_index(graphlab::gl_sframe sf, std::string colname) {
        ^
src/libffm.cpp:56:58: error: call of overloaded 'get_column_index(graphlab::gl_sframe&, std::basic_string<char>&)' is ambiguous
     feature_col_idxs.push_back(get_column_index(data, col));
                                                          ^
src/libffm.cpp:56:58: note: candidates are:
src/libffm.cpp:22:8: note: size_t get_column_index(graphlab::gl_sframe, std::string)
 size_t get_column_index(gl_sframe sf, string colname) {
        ^
In file included from src/libffm.cpp:16:0:
../sdk/../ffm/lib/ffm.h:22:8: note: size_t ffm::get_column_index(graphlab::gl_sframe, std::string)
 size_t get_column_index(graphlab::gl_sframe sf, std::string colname) {
        ^
make: *_\* [libffm.so] Error 1

**Comment by chrisdubois** [comment]
Thanks for reporting! Fixed by dce0d58f666e0e97006d6df9af322fc4f9c8c782.
